### ISSUE TITLE
Add OpenAPI to Postman Network

### ISSUE THREAD

**Issue by kinlane** [blockfrost/openapi#157]
Hello there, nice work on your OpenAPI. I'd love to see a Blockfrost team added to the [Postman API network](https://www.postman.com/postman), and your OpenAPI imported into a public workspace for our users to put to use. Appreciate the consideration!

**Comment by mmahut** [comment]
Hello Kim,

I just published the API at https://www.postman.com/blockfrost-io/workspace/my-workspace/api/5219e440-dbf0-4f1b-9ed2-ad0023ccd88e.
