### ISSUE TITLE
.NET SDK Not Listed on Docs

### ISSUE THREAD

**Issue by soyfrien** [blockfrost/openapi#182]
I have spent some time trying to get generators to build classes to work with your OpenAPI spec, and learning they are far from perfect.

Would you please list https://github.com/blockfrost/blockfrost-dotnet on your [official docs](https://docs.blockfrost.io/#section/SDKs), so others can avoid messing around with tools they don't need?

Thank you!

**Comment by soyfrien** [comment]
Should solve https://github.com/blockfrost/blockfrost-dotnet/issues/46

**Comment by 1000101** [comment]
Oh my, you're absolutely right! Thanks for letting us know it's missing and sorry for the inconvenience this have caused you.

**Comment by soyfrien** [comment]
No worries, thanks for the quick reply!
