### ISSUE TITLE
Specific account address api is not stable

### ISSUE THREAD

**Issue by yerycs** [blockfrost/openapi#274]
https://docs.blockfrost.io/#tag/Cardano-Accounts/paths/~1accounts~1%7Bstake_address%7D/get
This api is not stable. I tried this api dozens of times, I got success once, and got errors. 500, 503, 504.
Maybe, because of wallet has lots of transactions?

**Comment by 1000101** [comment]
Hi @yerycs , that can be the case. We will be deploying a new release addressing huge accounts soon. Since this is not an openapi problem, I am closing this issue. Please contact support for any further inquiries.
