### ISSUE TITLE
Support `additionalUtxoSet` for the `/utils/txs/evaluate` endpoint

### ISSUE THREAD

**Issue by jy14898** [blockfrost/openapi#276]
https://github.com/blockfrost/openapi/pull/187 introduced the `/utils/txs/evaluate` endpoint for evaluating script ex units, apparently as a proxy to Ogmios, but this endpoint provides no way to supply the `additionalUtxoSet` that the Ogmios query accepts: https://github.com/CardanoSolutions/ogmios/pull/181 and https://ogmios.dev/mini-protocols/local-tx-submission/#additional-utxo-set

The additional utxo set is useful for transaction chaining, as we can build and balance a second transaction, before submitting the first.

**Comment by vladimirvolek** [comment]
https://docs.blockfrost.io/#tag/Cardano-Utilities/paths/~1utils~1txs~1evaluate~1utxos/post
