### ISSUE TITLE
Lovelace Power per Epoch Per Stake Address

### ISSUE THREAD

**Issue by matiwinnetou** [blockfrost/openapi#309]
While we already have ability to see stake power for a given epoch when somebody is staking. It would be nice to have an endpoint where we see stake power also for scenarios where somebody is not staking to any pool. Effectively such endpoint would add up all UTxOs belonging to a stake address.

One can ask the question, what is the point of this. Well for voting systems (stake based) one doesn't want to exclude people that are not staking... they may not be staking because of tax reasons.

**Comment by mmahut** [comment]
As long as the staking address is registrated, it should show up, there is no need to stake to a pool.
