### ISSUE TITLE
Given transaction hash return full transaction as cbor.

### ISSUE THREAD

**Issue by matiwinnetou** [blockfrost/openapi#310]
It would be desired to have an endpoint that given transaction hash simply returns the whole transaction body as cbor.

Such an endpoint is needed to deserialise transaction in various off-chain tools and exactly analyze it, e.g. check witness signatures.

**Comment by mmahut** [comment]
As we designed Blockfrost to provide interpretation of information about the blockchain, not serve the blob information directly, this is not a priority at the moment, but we might implement this in the future.

**Comment by slowbackspace** [comment]
implemented https://docs.blockfrost.io/#tag/cardano--transactions/GET/txs/{hash}/cbor
