### ISSUE TITLE
Support Version 2 of CIP 25

### ISSUE THREAD

**Issue by leo42** [blockfrost/openapi#319]
https://cips.cardano.org/cips/cip25/

CIP -25 (NFT onchain metadata registration ) has a V2 version now.

It is simply declaring Version: 2 and describing a token by the hex encoded name, instead of a simple string.

Is blockfrost planning to support this specification ?

**Comment by mmahut** [comment]
Blockfrost does support CIP25v2, see [/assets](https://docs.blockfrost.io/#tag/Cardano-Assets/paths/~1assets/get) endpoints with `onchain_metadata_standard`.

**Comment by leo42** [comment]
Is this available on the testnet (preprod) ?

I am trying to get the data for  "64b87bcae32aed7e122db37e202b014d55bbe739e0cdef4b317695b409ec6469b1f64c114d3ec2b2bc037ee4312cdb0a17787bf3aace9c40f39fc93c" but it returns no metadata. 


It is registerd with v2 metadata properly. 
[https://preprod.cardanoscan.io/transaction/305af876cce847a126a5a2890ecb97d5286782c03d87571ddfcb53ea951174ca?tab=tokenmint](url) 


current result:
{
    "asset": "64b87bcae32aed7e122db37e202b014d55bbe739e0cdef4b317695b409ec6469b1f64c114d3ec2b2bc037ee4312cdb0a17787bf3aace9c40f39fc93c",
    "policy_id": "64b87bcae32aed7e122db37e202b014d55bbe739e0cdef4b317695b4",
    "asset_name": "09ec6469b1f64c114d3ec2b2bc037ee4312cdb0a17787bf3aace9c40f39fc93c",
    "fingerprint": "asset1999jatn3x3dpggyf3z3fv64sw9hpqy65v0gzs7",
    "quantity": "1",
    "initial_mint_tx_hash": "4a366120d88128aa0e18b4656a834523b7a35455992f4c62dcca919e56396395",
    "mint_or_burn_count": 1,
    "onchain_metadata": null,
    "onchain_metadata_standard": null,
    "onchain_metadata_extra": null,
    "metadata": null
}
