### ISSUE TITLE
token metadata returning blank on the testnet  

### ISSUE THREAD

**Issue by leo42** [blockfrost/openapi#320]
I am trying to get the data for "64b87bcae32aed7e122db37e202b014d55bbe739e0cdef4b317695b409ec6469b1f64c114d3ec2b2bc037ee4312cdb0a17787bf3aace9c40f39fc93c" but it returns no metadata.

It is registerd with v2 metadata properly.
[https://preprod.cardanoscan.io/transaction/305af876cce847a126a5a2890ecb97d5286782c03d87571ddfcb53ea951174ca?tab=tokenmint](https://github.com/blockfrost/openapi/issues/url)

current result:
{
"asset": "64b87bcae32aed7e122db37e202b014d55bbe739e0cdef4b317695b409ec6469b1f64c114d3ec2b2bc037ee4312cdb0a17787bf3aace9c40f39fc93c",
"policy_id": "64b87bcae32aed7e122db37e202b014d55bbe739e0cdef4b317695b4",
"asset_name": "09ec6469b1f64c114d3ec2b2bc037ee4312cdb0a17787bf3aace9c40f39fc93c",
"fingerprint": "asset1999jatn3x3dpggyf3z3fv64sw9hpqy65v0gzs7",
"quantity": "1",
"initial_mint_tx_hash": "4a366120d88128aa0e18b4656a834523b7a35455992f4c62dcca919e56396395",
"mint_or_burn_count": 1,
"onchain_metadata": null,
"onchain_metadata_standard": null,
"onchain_metadata_extra": null,
"metadata": null
}

**Comment by mmahut** [comment]
It is not registered correctly, policy/assetname is not in bytes.

Please refer to the standard at https://cips.cardano.org/cips/cip25/#cddl.
