### ISSUE TITLE
Add witness data to transaction by transaction hash endpoint

### ISSUE THREAD

**Issue by matiwinnetou** [blockfrost/openapi#325]
In some cases it is necessary to validate witness data of a transaction and currently transaction endpoint is not returning verification keys (public keys). This eliminates it harder than necessary to develop on Cardano.

**Comment by sorki** [comment]
Hi, do you mean extra transaction witnesses (required signers)?

**Comment by matiwinnetou** [comment]
yes

**Comment by sorki** [comment]
Ok, we can add this.
