### ISSUE TITLE
pvtpp_security_group should be named pvt_pp_security_group to stay consistent.

### ISSUE THREAD

**Issue by RSoulatIOHK** [blockfrost/openapi#364]
All the pool voting thresholds are named pvt_xx except `pvtpp_security_group`.

`pvtpp_security_group` should be named `pvt_pp_security_group` to stay consistent with the rest of the naming.

**Comment by sorki** [comment]
Makes sense, we used the similar inconsistently named field from [`db-sync`s schema](https://github.com/IntersectMBO/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L473)

We will probably mark the `pvtpp_security_group` deprecated and a `pvt_pp_security_group` so it's backwards compatible.
